- name: Monitor new/updated apps for API calls
  hosts: all
  gather_facts: false
  vars:
    monitor_script: "C:\\Users\\ansible\\Desktop\\monitorsingle.py"
    python_path: "C:\\Users\\ansible\\AppData\\Local\\Programs\\Python\\Python313\\python.exe"

  tasks:

    - name: Monitor API calls for each changed app
      win_command: >
        {{ python_path }} {{ monitor_script }} "{{ item.name }}"
      register: monitor_output
      loop: "{{ changes[inventory_hostname] | default([]) }}"
      loop_control:
        label: "{{ item.name }}"
      changed_when: false
      failed_when: false

    - name: Show API results
      debug:
        msg: "{{ item.stdout | from_json }}"
      loop: "{{ monitor_output.results }}"
