- name: Run Procmon Monitor Script
  hosts: all
  tasks:
    - name: Run Python script using full path
      win_command: >
        C:\Users\PeterC\AppData\Local\Programs\Python\Python313\python.exe
        C:\Users\PeterC\Desktop\Procmon\monitor.py
