---
- name: Localized Yara Scan (Using Specific Rule File on Target) # Updated Name
  # This playbook performs localized static analysis (Yara scan) on a specific file
  # on an endpoint. It's triggered by a centralized system (AWX via Orin)
  # and uses a specific Yara rule file expected to already exist on the target machine.
  hosts: "{{ target_host_ip | default('localhost') }}" # Dynamically set by AWX extra_vars
  become: yes # Required for package installation and potentially accessing files
  gather_facts: yes

  vars:
    # --- Variables expected via AWX extra_vars ---
    # file_to_scan: # Mandatory, e.g., "/usr/bin/wget" provided by trigger script
    # target_host_ip: # Mandatory, e.g., "192.168.190.33" provided by trigger script

    # --- Configuration: Paths on the TARGET Machine (Linux Desktop) ---
    # Define the location where Yara rules *already exist* on the target.
    yara_rules_dir_on_target: "/home/peter/Desktop/rules"
    # Define the specific rule file to use
    yara_rule_file_name: "suspicious_binary_indicators.yar" # <<< ADDED Variable

    # --- Internal Playbook Vars ---
    yara_executable_on_target: "yara"
    # Combine directory and filename for convenience
    yara_rule_full_path: "{{ yara_rules_dir_on_target }}/{{ yara_rule_file_name }}" # <<< ADDED Variable

  pre_tasks:
    - name: Validate mandatory input variables
      ansible.builtin.assert:
        that:
          - file_to_scan is defined
          - file_to_scan | length > 0
          - target_host_ip is defined
        fail_msg: "Mandatory variable 'file_to_scan' must be provided via AWX extra_vars."
        quiet: yes

  tasks:
    - name: "Setup Phase: Ensure Yara package is present on target '{{ inventory_hostname }}'"
      ansible.builtin.package:
        name: "{{ yara_executable_on_target }}"
        state: present
      register: pkg_result
      failed_when: pkg_result is failed and "No package matching" not in pkg_result.msg | default('') and "Nothing to do" not in pkg_result.msg | default('')

    - name: "Setup Phase: Verify Yara executable exists on target"
      ansible.builtin.command: "which {{ yara_executable_on_target }}"
      register: yara_which_check
      changed_when: false
      failed_when: false
      check_mode: no

    - name: "Setup Phase: Verify Yara rule file exists on target" # <<< MODIFIED Task Name
      ansible.builtin.stat:
        path: "{{ yara_rule_full_path }}" # <<< MODIFIED: Check specific file path
      register: rule_file_stat # <<< MODIFIED Variable Name
      when: yara_which_check.rc == 0

    - name: "Analysis Phase: Check if target file '{{ file_to_scan }}' exists"
      ansible.builtin.stat:
        path: "{{ file_to_scan }}"
      register: file_stat
      when: yara_which_check.rc == 0

    - name: "Analysis Phase: Execute Yara scan (Using specific rule file on target)" # <<< MODIFIED Task Name
      ansible.builtin.command:
        # -w: disable warnings
        # Point directly to the specific rule file on the target
        cmd: "{{ yara_executable_on_target }} -w {{ yara_rule_full_path }} {{ file_to_scan }}" # <<< MODIFIED Command
      register: yara_result
      failed_when: yara_result.rc > 1
      changed_when: false
      when:
        - yara_which_check.rc == 0
        - rule_file_stat.stat is defined and rule_file_stat.stat.exists and rule_file_stat.stat.isreg # <<< MODIFIED: Check rule file exists/isreg
        - file_stat.stat is defined and file_stat.stat.exists and file_stat.stat.isreg

    - name: "Reporting Phase: Display Yara Scan Results (if matches or errors)"
      ansible.builtin.debug:
        msg:
          - "YARA Scan Result on {{ inventory_hostname }} for file: {{ file_to_scan }}"
          - "Triggered by: Centralized Behaviour Monitoring (via AWX)"
          - "Using Rule File From Target Path: {{ yara_rule_full_path }}" # <<< MODIFIED Message
          - "Scan Command: {{ yara_result.cmd | default('N/A') }}"
          - "Return Code: {{ yara_result.rc }}"
          - "Matches/Output (stdout):"
          - "{{ yara_result.stdout | default('(No Matches Found)') }}"
          - "Errors (stderr): {{ yara_result.stderr | default('(No Errors)') }}"
      when: yara_result is defined and (yara_result.rc != 0 or yara_result.stderr | length > 0)

    - name: "Reporting Phase: Note if target file was not found/scannable"
      ansible.builtin.debug:
        msg: "YARA Scan Skipped on {{ inventory_hostname }}: Target file '{{ file_to_scan }}' not found, not a regular file, or prerequisite step failed."
      when: yara_which_check.rc == 0 and (yara_result is not defined or yara_result is skipped or (not file_stat.stat.exists or not file_stat.stat.isreg))

    - name: "Reporting Phase: Note if Yara rule file was not found on target" # <<< MODIFIED Task Name & Message
      ansible.builtin.debug:
        msg: "YARA Scan Skipped on {{ inventory_hostname }}: Pre-existing rule file '{{ yara_rule_full_path }}' not found or not a regular file."
      when: yara_which_check.rc == 0 and (rule_file_stat.stat is not defined or not rule_file_stat.stat.exists or not rule_file_stat.stat.isreg) # <<< MODIFIED Condition

    - name: "Reporting Phase: Note if Yara executable was not found"
      ansible.builtin.debug:
        msg: "YARA Scan Failed on {{ inventory_hostname }}: '{{ yara_executable_on_target }}' command not found on target system."
      when: yara_which_check.rc != 0

  post_tasks: []
